# Working with Dates

## Load libs
```{r}
library(tidyverse)
```

```{r}
# create date matrix
df <- expand.grid(month=seq(1,12,1),
                  day=seq(1,31,1),
                  year=seq(1930,2030)) %>%
  mutate(mdy = lubridate::mdy(paste0(month,"/",day,"/",year))) %>%
  mutate(weekday = lubridate::wday(mdy),
         weekday_l = lubridate::wday(mdy, label=T)) %>%
  filter(!is.na(weekday))

```

```{r}

# mark specific dates
df_marked <- df %>%
  mutate(cinco_de_mayo_taco_tuesday = ifelse(month == 5 &
                                day == 5 &
                                weekday_l == "Tue", 1, 0),
         friday_13th = ifelse(day == 13 &
                                weekday_l == "Fri", 1, 0),
         erica_bday = ifelse(day == 4 &
                               month == 4, 1, 0))

# segment days Alexa mentioned
all_cinco_de_mayo_taco_tuesday <- df_marked %>%
  filter(cinco_de_mayo_taco_tuesday == 1)

all_friday13th <- df_marked %>%
  filter(friday_13th == 1)

all_erica <- df_marked %>%
  filter(erica_bday == 1) %>%
  filter(year >= 1991)

```

## Count wife birthday by day of week
```{r}
erica_wkday <- all_erica %>%
  group_by(weekday_l) %>%
  summarise(n = n())

```

## Plot time series of Cinco de Mayo landing on a Tuesday (Taco Tuesday!)

```{r}

ggplot(df_marked, aes(year, cinco_de_mayo_taco_tuesday)) +
  geom_tile() +
  theme_minimal()

ggplot(df_marked, aes(year, cinco_de_mayo_taco_tuesday)) +
  geom_path() +
  theme_minimal()

ggplot(erica_wkday, aes(weekday_l, n, group=weekday_l, fill=weekday_l)) +
  geom_bar(stat="identity")
```
